In [22]:
import numpy as np
import open3d as o3d
import pandas as pd

df = pd.read_csv("./1_coche.csv")
nube = df[["x", "y", "z"]]

print(df)
print(nube)

                x         y          z  intensity           t  reflectivity  \
0       -0.000000  0.000000   0.000000        0.0  1181241184             0   
1       -0.000000  0.000000   0.000000       16.0           0             0   
2       -0.000000  0.000000   0.000000       13.0       49720             0   
3      -13.000649  2.733196  13.144561       14.0       99080             3   
4      -12.894675  2.793606  13.054574       12.0      150920             2   
...           ...       ...        ...        ...         ...           ...   
131067  -0.000000 -0.000000  -0.000000        0.0  1181241184             0   
131068  -0.000000 -0.000000  -0.000000        0.0  1181241184             0   
131069  -0.000000 -0.000000  -0.000000        0.0  1181241184             0   
131070  -0.000000 -0.000000  -0.000000        0.0  1181241184             0   
131071  -0.000000 -0.000000  -0.000000        0.0  1181241184             0   

        ring  ambient  range  
0          0        

In [19]:
#nube = o3d.io.read_point_cloud("./carretera.csv")
print(nube)
print(np.asarray(nube[["x", "y", "z"]]))

                x         y          z
0       -0.000000  0.000000   0.000000
1       -0.000000  0.000000   0.000000
2       -0.000000  0.000000   0.000000
3      -13.000649  2.733196  13.144561
4      -12.894675  2.793606  13.054574
...           ...       ...        ...
131067  -0.000000 -0.000000  -0.000000
131068  -0.000000 -0.000000  -0.000000
131069  -0.000000 -0.000000  -0.000000
131070  -0.000000 -0.000000  -0.000000
131071  -0.000000 -0.000000  -0.000000

[131072 rows x 3 columns]
[[-0.  0.  0.]
 [-0.  0.  0.]
 [-0.  0.  0.]
 ...
 [-0. -0. -0.]
 [-0. -0. -0.]
 [-0. -0. -0.]]


In [20]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.asarray(nube[["x", "y", "z"]]))

In [21]:
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])